# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-06 02:14
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_brand', models.CharField(max_length=200, unique=True)),
                ('banner_brand', models.ImageField(blank=True, null=True, upload_to='images/banner_brands')),
                ('created_at_brand', models.DateTimeField(auto_now_add=True)),
                ('updated_at_brand', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=200, unique=True)),
                ('description_category', models.TextField(blank=True, null=True)),
                ('banner_category', models.ImageField(blank=True, null=True, upload_to='images/banner_categories')),
                ('sort_order_category', models.IntegerField(default=0)),
                ('status_category', models.BooleanField()),
                ('slug_category', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name_category', unique=True)),
                ('created_at_category', models.DateTimeField(auto_now_add=True)),
                ('updated_at_category', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_image', models.CharField(max_length=200, unique=True)),
                ('image_image', models.ImageField(blank=True, null=True, upload_to='images/products')),
                ('created_at_image', models.DateTimeField(auto_now_add=True)),
                ('updated_at_image', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=100, unique=True)),
                ('extract_product', models.CharField(max_length=100)),
                ('description_product', models.TextField()),
                ('slug_product', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name_product', unique=True)),
                ('sku_product', models.CharField(max_length=100, unique=True)),
                ('price_product', models.DecimalField(decimal_places=2, max_digits=11)),
                ('rating_product', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('status_product', models.BooleanField()),
                ('created_at_product', models.DateTimeField(auto_now_add=True)),
                ('updated_at_product', models.DateTimeField(auto_now=True)),
                ('brand_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_pi', models.DateTimeField(auto_now_add=True)),
                ('updated_at_pi', models.DateTimeField(auto_now=True)),
                ('image_pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Image')),
                ('product_pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_slider', models.CharField(max_length=100, unique=True)),
                ('image_slider', models.ImageField(blank=True, null=True, upload_to='images/sliders')),
                ('description_slider', models.TextField()),
                ('sort_order_slider', models.IntegerField(default=0)),
                ('status_slider', models.BooleanField()),
                ('created_at_slider', models.DateTimeField(auto_now_add=True)),
                ('updated_at_slider', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subcategory', models.CharField(max_length=200, unique=True)),
                ('icon_subcategory', models.ImageField(blank=True, null=True, upload_to='images/icons_subcategories')),
                ('sort_order_subcategory', models.IntegerField(default=0)),
                ('status_subcategory', models.BooleanField()),
                ('slug_subcategory', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name_subcategory', unique=True)),
                ('created_at_subcategory', models.DateTimeField(auto_now_add=True)),
                ('updated_at_subcategory', models.DateTimeField(auto_now=True)),
                ('category_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Subcategory'),
        ),
    ]
