# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-06 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='sort_order_image',
            field=models.IntegerField(default=0),
        ),
    ]
